# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing_one', models.UUIDField(default=uuid.uuid4)),
                ('thing_two', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
